version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: "monitoring-grafana"
    ports:
      - "3000:3000"
    volumes:
       - $PWD/grafana-storage:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_LOG_MODE=console file
    networks:
      - grafana
  prometheus:
    image: prom/prometheus:latest
    container_name: "monitoring-prometheus"
    ports:
      - "9090:9090"
    volumes:
      - $PWD/prometheus-config:/etc/prometheus
    networks:
      - grafana

networks:
  grafana: