version: "3.8"

services:
  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform-container
  terragrunt:
    image: alpine/terragrunt:latest
    container_name: terragrunt-container