version: "3.8"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres-container
    ports:
        - "5432:5432"
    volumes:
        - $PWD/pgdata:/var/lib/postgresql/data
    restart: always
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        #POSTGRES_DB=petfinderdb

#https://betterprogramming.pub/tired-of-installing-databases-use-docker-instead-7e193be458cf