version: "3.8"
services:
  nexus:
    image: sonatype/nexus:latest
    container_name: nexus-container
    ports:
      - "8082:8081"
    volumes:
      - $PWD/nexus-data:/nexus-data
      #- ./nexus-data:/nexus-data