version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-container
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $PWD/docker-volume-testing:/var/jenkins_home
      
# $PWD: This will store the jenkins data in /your/home on the host; /var/jenkins_home: This will store the workspace in /var/jenkins_home