version: "3.8"

services:
  jenkins:
    container_name: jenkins-container
    build:
      context: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $PWD/docker-volume-testing:/var/jenkins_home