version: "3.8"

services:
  mongodb:
    image: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=YOUR_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=YOUR_PASSWORD
